Repository WildAid/o-fish-realm, pull requests merged in 2020-09, with the labels that each got.

#123 Update README.md
  README.md
Labels: documentation

#120 Current app showing and grouping fixes
  WildAidDemo/functions/searchFacetByCrews/source.js
  WildAidDemo/functions/searchFacetByVessels/source.js
Labels: bug, enhancement

#125 Update README.md
  README.md
Labels: documentation

#131 Search on email/agency name correctly
  WildAidDemo/functions/isAgencyMember/source.js
Labels: bug

#132 Add a flag to the BoardingReport schema to indicate whether the report is currently a draft
  WildAidDemo/services/RealmSync/rules/wildaid.BoardingReports.json
  WildAidDemo/services/mongodb-atlas/rules/wildaid.BoardingReports.json
Labels: days: 0.25, desirable: Production, enhancement

#137 Add roles to allow agency admins and officers to access `Agency` docs
  WildAidDemo/services/mongodb-atlas/rules/wildaid.Agency.json
Labels: days: 0.25, enhancement

#139 Add function to allow anon user to create new User and Agency docs
  README.md
  WildAidDemo/functions/regNewAgency/config.json
  WildAidDemo/functions/regNewAgency/source.js
Labels: enhancement
